### ISSUE TITLE
How to set up parallel computing

### ISSUE THREAD

**Issue by USTCNing** [kaanaksit/odak#26]
There is lots of time in holographic calculation and Sommerfeld diffraction integration.Here we can optimize the parallel calculation to speed up the time. But I don’t know how to do it.

**Comment by kunguz** [comment]
@USTCNing Thank you for using `odak`. I received your enquiry. Please stay tuned for updates. I will keep you informed as we add this functionality of propagating multiple holograms in parallel. I will echo this to this issue when it is time.

I am mentioning @KorayKavakli to give him visibility!
