### ISSUE TITLE
A question about calculating the pooling area in make_pooling_size_map_pixels

### ISSUE THREAD

**Issue by Bob-Yeah** [kaanaksit/odak#55]
If I understand it right, in order to calculate the major_axis of the ellipse here
https://github.com/kaanaksit/odak/blob/master/odak/learn/perception/foveation.py#L130
a multiplication is required according to simple trigonometric function  as
major_axis = (torch.tan(angle_max) - torch.tan(angle_min))  * real_viewing_distance
But a division is used in the your code.
I'm wondering if it is a bug or I misunderstand your code.

**Comment by drwalton** [comment]
Thank you for highlighting this - you're correct about the computation, there should be a multiplication rather than a division here. I've submitted a correction to this now.

**Comment by kaanaksit** [comment]
@Bob-Yeah, Please do not hesitate to let us know if 1e3cdc89bc70383c2bed62280b526ae9a2731acc resolves this issue. In the meantime, the portion of the code that you have highlighted is part of this specific paper:

```bibtex
@article{walton2021beyond,
    author = {David R. Walton and Rafael Kuffner Dos Anjos and Sebastian Friston and David Swapp and Kaan Akşit and Anthony Steed and Tobias Ritschel},
    title    = {Beyond Blur: Ventral Metamers for Foveated Rendering},
    journal = {ACM Trans. Graph. (Proc. SIGGRAPH 2021)},
    year = {2021},
    volume = {40},
    number = {4},
}
```

Odak could be best cited following the information found in [this link](https://github.com/kaanaksit/odak#how-to-cite). Wewould  appreciate if you could give this repository a star on GitHub. For now, I will close this issue.
