### ISSUE TITLE
AttributeError: 'display_color_hvs' object has no attribute 'rgb_to_lms'

### ISSUE THREAD

**Issue by yilmazdoga** [kaanaksit/odak#88]
Hello,

I intended to use the `__call__` function of the `display_color_hvs` class in `odak.learn.perception.color_conversion.py`. However, since the `self.rgb_to_lms` function is deprecated, I encountered the following error:

```
lms_image_second = self.rgb_to_lms(input_image.to(self.device))
AttributeError: 'display_color_hvs' object has no attribute 'rgb_to_lms'
```
To reproduce the issue, I have prepared an isolated example below:

```python
import torch
from PIL import Image
from torchvision import transforms
from odak.learn.perception.color_conversion import display_color_hvs

image_path = 'data/parrot.png'
preprocess = transforms.Compose([
        transforms.ToTensor(),           
    ])

image = Image.open(image_path)
tensor_image = preprocess(image)

dc_hvs = display_color_hvs(read_spectrum = 'default')
loss = dc_hvs(tensor_image, tensor_image)
```

With the current design, is there a workaround to obtain equivalent functionality?

**Comment by aguzel** [comment]
Dear Doga, 

The new version `Odak` is using implicit implementation of primaries (RGB in your case) to LMS space which you should input your display spectrum for all primaries available between 400nm and 700nm. Previously it was explicitly defined by a generic display spectrum (RGB). 

For example,  you assign your primaries to `target_primaries`, and conversion is done by `display_color.primaries_to_lms(target_primaries)`. You can find more details in `Odak` documentation.

**Comment by yilmazdoga** [comment]
Dear Ahmet,

Thank you for your quick response and clarification. I will try the new implicit implementation method.
